name = "cloudflare-news-hub"
main = "index.js"
compatibility_date = "2024-03-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "NEWS_CONFIG"
id = "26d72d9d4753437cb16a70b67bb71507"

[triggers]
crons = ["*/30 * * * *"]
